FROM python:3.7-buster
FROM ubuntu:18.04

RUN git clone https://github.com/GrzegorzMika/Morozov.git

COPY secretgc_ip.json /home/Morozov

WORKDIR /home/Morozov

RUN pip install -r requirements.txt

CMD python TransformedMeasure_TSVD.py && python upload.py

