FROM python:3.7-buster
FROM ubuntu:18.04

RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y python3-pip

RUN mkdir /home/Morozov

WORKDIR /home/Morozov

COPY . .
COPY secretgc_ip.json /home/Morozov

RUN pip3 install -r ./requirements.txt

RUN pip3 install dask distributed --upgrade

CMD python3 Tikhonov_tr2.py && python3 -c "from utils import upload; upload()"

